[package]
name = "strata-server"
version = "0.1.0"
edition = "2021"

[dependencies]
strata-storage = { workspace = true }
strata-consensus = { workspace = true }
strata-sharding = { workspace = true }
strata-index = { workspace = true }
strata-txn = { workspace = true }
strata-net = { workspace = true }
strata-planner = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
